Ext.define("EntityProperty.view.BaseInfoForm", {
    extend: 'Ext.ng.TableLayoutForm',
    xtype: 'baseInfoForm',
    buskey: 'id',
    title: '基本信息',
    split: true,
    autoScroll: true,
    otype: otype,
    columnsPerRow: 3,
    fields: [{
        id: 'Name',
        xtype: 'ngText',
        fieldLabel: '名称',
        mustInput: true, 
        name: 'Name'
    }, {
        id: 'CurrentDisplayName',
        xtype: 'ngText',
        fieldLabel: '显示名称',
        mustInput: true, 
        name: 'CurrentDisplayName'
    }, {
        id: 'Namespace',
        xtype: 'ngText',
        fieldLabel: '命名空间',
        mustInput: true, 
        name: 'Namespace'
    }, {
        id: 'Version',
        xtype: 'ngText',
        mustInput: true, 
        fieldLabel: '版本',
        name: 'Version'
    }, {
        xtype: 'combo',
        store: yesAndNo,
        fieldLabel: '模版',
        queryMode: 'local',
        id: 'IsTemplate',
        name: 'IsTemplate',
        valueField: 'value',
        displayField: 'text'
    }, {
        xtype: 'combo',
        store: dataTypeStore,
        fieldLabel: '数据类型',
        queryMode: 'local',
        id: 'DataType',
        name: 'DataType',
        mustInput: true, //必输列
        valueField: 'value',
        displayField: 'text'
    }, {
        id: 'DefaultValue',
        xtype: 'ngText',
        fieldLabel: '默认值',
        name: 'DefaultValue'
    }, {
        id: 'MaxStringLength',
        xtype: 'ngNumber',//'numberfield',
        fieldLabel: '字符长度',
        name: 'MaxStringLength'
    }, {
        id: 'MaxNumLength',
        xtype: 'ngNumber',//'numberfield',
        fieldLabel: '小数长度',
        name: 'MaxNumLength'
    }, {
        id: 'MaxNumPrecision',
        xtype: 'ngNumber',//'numberfield',
        fieldLabel: '小数精度',
        name: 'MaxNumPrecision'
    }, {
        xtype: 'combo',
        store: yesAndNo,
        fieldLabel: '非空',
        queryMode: 'local',
        id: 'IsAllowNull',
        name: 'IsAllowNull',
        valueField: 'value',
        displayField: 'text'
    }, {
        xtype: 'combo',
        store: yesAndNo,
        fieldLabel: '唯一',
        queryMode: 'local',
        id: 'IsAllowRepeat',
        name: 'IsAllowRepeat',
        valueField: 'value',
        displayField: 'text'
    }, {
        id: 'MapFieldName',
        xtype: 'ngText',
        fieldLabel: '映射字段',
        mustInput: true, //必输列
        name: 'MapFieldName'
    }, {
        xtype: 'combo',
        store: yesAndNo,
        fieldLabel: '计算字段',
        queryMode: 'local',
        id: 'IsCompute',
        name: 'IsCompute',
        valueField: 'value',
        displayField: 'text'
    }, {
        id: 'ComputeExpression',
        xtype: 'ngTextArea',
        fieldLabel: '计算表达式',
        name: 'ComputeExpression',
        colspan: 3
    }, {
        xtype: 'ngTextArea',
        fieldLabel: '备注',
        name: 'Remark',
        colspan: 3
    },{
        id: 'Id',
        xtype: 'hiddenfield',
        fieldLabel: '编号',
        name: 'Id'
    }, {
        id: 'ParentId',
        xtype: 'hiddenfield',
        fieldLabel: '父亲节点编号',
        name: 'ParentId'
    }, {
        id: 'ParentVersionId',
        xtype: 'hiddenfield',
        fieldLabel: '父亲节点版本编号',
        name: 'ParentVersionId'
    }, {
        id: 'DisplayName',
        xtype: 'hiddenfield',
        fieldLabel: '显示名称',
        name: 'DisplayName'
    }]
});