Ext.define("Entity.view.BaseInfoForm", {
    extend: 'Ext.ng.TableLayoutForm',
    xtype: 'baseInfoForm',
    buskey: 'id',
    title: '基本信息',
    split: true,
    autoScroll: true,
    otype: otype,
    columnsPerRow: 3,
    fields: [{
        id: 'Name',
        xtype: 'ngText',
        fieldLabel: '名称',
        name: 'Name',
        mustInput: true
    }, {
        id: 'CurrentDisplayName',
        xtype: 'ngText',
        fieldLabel: '显示名称',
        labelWidth: 80,
        name: 'CurrentDisplayName',
        mustInput: true
    }, {
        id: 'Namespace',
        xtype: 'ngText',
        fieldLabel: '命名空间',
        labelWidth: 80,
        mustInput: true, 
        name: 'Namespace'
    }, {
        id: 'Version',
        xtype: 'ngText',
        fieldLabel: '版本',
        mustInput: true,
        name: 'Version'
    }, {
        id: 'KeyMapColumn',
        xtype: 'ngText',
        fieldLabel: '主键映射字段',
        labelWidth: 80,
        mustInput: true,
        name: 'KeyMapColumn'
    }, {
        xtype: 'combo',
        store: dataTypeStore,
        fieldLabel: '主键数据类型',
        queryMode: 'local',
        id: 'KeyDataType',
        name: 'KeyDataType',
        mustInput: true, //必输列
        valueField: 'value',
        displayField: 'text'
    }, {
        xtype: 'combo',
        store: keyGenerateStyleStore,
        labelWidth: 80,
        fieldLabel: '主键产生方式',
        queryMode: 'local',
        id: 'KeyGenerateStyle',
        name: 'KeyGenerateStyle',
        valueField: 'value',
        displayField: 'text'
    }, {
        xtype: 'combo',
        store: yesAndNo,
        fieldLabel: '树形展示',
        queryMode: 'local',
        id: 'IsTreeStyle',
        name: 'IsTreeStyle',
        valueField: 'value',
        displayField: 'text'
    }, {
        id: 'ParentNodePropertyId',
        xtype: 'ngText',
        fieldLabel: '父节点属性',
        labelWidth: 80,
        name: 'ParentNodePropertyId'
    }, {
        id: 'ChildNodePropertyId',
        xtype: 'ngText',
        fieldLabel: '子节点属性',
        labelWidth: 80,
        name: 'ChildNodePropertyId'
    }, {
        id: 'UpdateTable',
        xtype: 'ngText',
        fieldLabel: '更新表',
        name: 'UpdateTable'
    }, {
        xtype: 'ngTextArea',
        fieldLabel: 'SQL语句',
        name: 'Sql',
        colspan: 3
    }, {
        xtype: 'ngTextArea',
        fieldLabel: '备注',
        name: 'Remark',
        colspan: 3
    }, {
        id: 'Id',
        xtype: 'hiddenfield',
        fieldLabel: '编号',
        name: 'Id'
    }, {
        id: 'ParentId',
        xtype: 'hiddenfield',
        fieldLabel: '父亲节点编号',
        name: 'ParentId'
    }, {
        id: 'ParentVersionId',
        xtype: 'hiddenfield',
        fieldLabel: '父亲节点版本编号',
        name: 'ParentVersionId'
    }, {
        id: 'DisplayName',
        xtype: 'hiddenfield',
        fieldLabel: '显示名称',
        name: 'DisplayName'
    }]
});